---
# tasks file for ec2
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-create-ec2"
    region: "us-west-2"
    key_name: "ansible-learning-key"
    # vpc_subnet_id: default
    instance_type: "{{type}}" # Variables from vars folder
    # security_group: default
    aws_access_key: "{{ec2_access_key}}"  # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined  
    network_interfaces:
      - assign_public_ip: true
    image_id: "{{ami_id}}" # AMI from defaults to show various sections of variables
    tags:
      Environment: ansible-learning