---
## Before running this we need to setup password less authentication to spun up instances
## Use ssh-copy-id -i <pem location> user@ip
# - hosts: all
#   become: true
#   name: Play where all running instances are terminated
#   tasks:
#     - name: Terminate every running instance in a region. Use with EXTREME caution.
#       amazon.aws.ec2_instance:
#         state: absent
#         filters:
#           instance-state-name: running

# - hosts: all
#   become: true
#   name: Play to check the ansible gathered ansible_facts
#   tasks:
#     - name: Show facts available on the system
#       ansible.builtin.debug:
#         var: ansible_facts

- hosts: all
  become: true
  name: Play that Terminates only ubuntu family instances
  tasks:
    - name: Terminate ubuntu instances
      ansible.builtin.command: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == "RedHat"
